### Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "eeramirez",
  "password": "912522Pop"
}

### register
POST https://tuvansacloud.dyndns.org/api/auth/register
Content-Type: application/json

{
  "username": "eeramirez",
  "name": "Erick",
  "last": "Ramirez",
  "branchOffice": "Mexico",
  "password": "912522Pop",
  "rol": "admin",
  "gender": "male",
  "pagePermission":[]
}

### register
POST https://tuvansacloud.dyndns.org/api/auth/register
Content-Type: application/json

{
  "username": "mavalos",
  "name": "Marcos",
  "last": "Avalos",
  "branchOffice": "Mexico",
  "password": "mph*772-",
  "rol": "user",
  "gender": "male",
  "pagePermission":["shipments", "sales"]
}

### renew token 
POST http://localhost:4000/api/auth/renew
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGFiMWZkN2VkMjg1ZmIzNThhOTQ2ZSIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzAxMjA5MTc1LCJleHAiOjE3MDEyMTI3NzV9.SKqZeE7SBIlW4AUUPtbpVwNmbw2j4Ong76G-KPnNOkM