### Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "eeramirez",
  "password": "912522Pop"
}

### register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "gbarranco",
  "name": "german",
  "last": "Barranco",
  "branchOffice": "Mexico",
  "password": "912522Pop"
}