### Get All categories
GET http://localhost:4000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA3NDI0MDQ4LCJleHAiOjE3MDc0MzEyNDh9.TojmALkaIZbokN7IrSWKM85h_-Gb1WdfHXqgWNy4354