GET http://localhost:4000/api/competitions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA5NzcwMTI5LCJleHAiOjE3MDk3NzczMjl9.R3juHYWLiqEzh8gOi27Bu4an_MmJGZR01UMjvNTfmO4

### Get by RFC EMISOR
GET http://localhost:4000/api/competitions/LAV751101B63?EfectoComprobante=Ingreso
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA4Mzc5NTk1LCJleHAiOjE3MDgzODY3OTV9._fNpRU0w63lvkYMT3NxWolPdCAtyDZ2ti63WHyGVceI
Content-Type: application/json

### Get customers by RFC Emisor
GET http://localhost:4000/api/competitions/customers/EGU800818ST2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA4MzA3OTY1LCJleHAiOjE3MDgzMTUxNjV9.rEKczb4pLhWobezTCWch_SUC4zYTzckegc0lcfLyu1Y


### Get Recibidas by Receptor
GET http://localhost:4000/api/competitions/recibidas/EGU800818ST2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA5NzcwMTI5LCJleHAiOjE3MDk3NzczMjl9.R3juHYWLiqEzh8gOi27Bu4an_MmJGZR01UMjvNTfmO4


### Get Recibidas by Emisor
GET http://localhost:4000/api/competitions/recibidas/emisor/TAM520130D49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA5Nzg1MTE2LCJleHAiOjE3MDk3OTIzMTZ9.U9gYtC_Yh4ae83D2-NvlA5TDRJACHhgzDkxqS0QZWIM