### create a Inventory
POST http://localhost:4000/api/inventories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA1NDU3MTExLCJleHAiOjE3MDU0NjQzMTF9.ejdjrIKbrW6k0fR5eg_K4lZzdd-mOLFW1Ui8n7vFem4

{

  "iseq":"21180",
  "cod":"01298372sssswww",
  "ean":"ACC/JU8sss9sswww",
  "description":" Tubo test",
  "quantity":0,
  "count": 1,
  "costo": 34.56,
  "branchOffice":{
    "code":"01",
    "name":"Mexico"
  }

}

### Update
PATCH http://localhost:4000/api/inventories/65a745e0af5a2ffb1027874a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA1NDU3MTExLCJleHAiOjE3MDU0NjQzMTF9.ejdjrIKbrW6k0fR5eg_K4lZzdd-mOLFW1Ui8n7vFem4

{
  "paused": false
}

### Get inventory by id
GET http://localhost:4000/api/inventories/657f55a51377677d2bc8a47f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA1NDQ2MDQ1LCJleHAiOjE3MDU0NTMyNDV9.-OayMTKymuPEgkGccK2BpdECUJ32H8vYY-PFtkVyONY
### Get by Iseq
GET http://localhost:4000/api/inventories/iseq/21294
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA1NDQ2MDQ1LCJleHAiOjE3MDU0NTMyNDV9.-OayMTKymuPEgkGccK2BpdECUJ32H8vYY-PFtkVyONY


### Get All inventories
GET http://localhost:4000/api/inventories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzEyMzQ0OTE0LCJleHAiOjE3MTIzNTIxMTR9.Baj2FO2CYwPMrFwPAmTU2dOMYbE4DkzXkBBWUcpEOCo


### Release Inventories
PUT http://localhost:4000/api/inventories/releaseall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzA1Njg3ODI4LCJleHAiOjE3MDU2OTUwMjh9.SoUrOjcD_L8ZhldCdC8IVa_eAgU6-aJax2jHS8qnGAc

{
  "paused": false
}