### create a Inventory
POST http://localhost:4000/api/inventories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzAyODQzNjQ5LCJleHAiOjE3MDI4NDcyNDl9.P_qxfg-poevzvEo74r8CLVl03ljI3iG-_p5gsJUV4EQ

{

  "iseq":"12562356",
  "cod":"01298372ss",
  "ean":"ACC/JU8sss9",
  "description":" Tubo test",
  "quantity":19.56,
  "count": 1289

}

### Update
PATCH http://localhost:4000/api/inventories/657e822c9ffbe509d27ca6c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzAyODM5NTMwLCJleHAiOjE3MDI4NDMxMzB9.W07TWR0Sx2uvn_AVxG7sElLiuagIraW-sHNrPA29HKc

{
  "paused": true
}

### Get inventory by id
GET http://localhost:4000/api/inventories/657f55a51377677d2bc8a47f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzAyODQ0MjY5LCJleHAiOjE3MDI4NTE0Njl9.ZSxz3vWPcmbuDuslV8KwVzsidigERzTf1uJWZppL90w

### Get by Iseq
GET http://localhost:4000/api/inventories/iseq/213263
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzAyODQ0MjY5LCJleHAiOjE3MDI4NTE0Njl9.ZSxz3vWPcmbuDuslV8KwVzsidigERzTf1uJWZppL90w


### Get All inventories
GET http://localhost:4000/api/inventories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzAzMDEwNDM0LCJleHAiOjE3MDMwMTc2MzR9.3iOjolhXKBZImbDkxNhZExsLunSr9vgbcfjHd5rdU98