GET https://tuvansacloud.dyndns.org/api/inventories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzEyMzQ0OTE0LCJleHAiOjE3MTIzNTIxMTR9.Baj2FO2CYwPMrFwPAmTU2dOMYbE4DkzXkBBWUcpEOCo

### Get inventory by id
GET https://tuvansacloud.dyndns.org/api/inventories/6581c83eb3bacbe01699d40a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzEyMzU2OTcxLCJleHAiOjE3MTIzNjQxNzF9.mvbeLBqESaHOQ7aXdyu9NsFxsvzRmwfUnc7HN4P1Z0I

### Get by Iseq
GET https://tuvansacloud.dyndns.org/api/inventories/iseq/3186
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmUyODE2Y2U1M2MyZTBkZTY5NzkwYiIsInVzZXJuYW1lIjoiZWVyYW1pcmV6IiwiaWF0IjoxNzEyNTE2NjI2LCJleHAiOjE3MTI1MjM4MjZ9.rqqZtq39akILr7UK1VFbkg8IhI6QdjYlGoch7H19rGw