### Create User
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "username": "eeramirez",
  "name": "Erick",
  "password": "912522Pop",
  "last": "Ramirez",
  "branchOffice": "Mexico",
  "rol": "admin"
}